### ISSUE TITLE
Help with anemometer please

### ISSUE THREAD

**Issue by pejandro5** [rpurser47/weatherstation#1]
I used the exact code for the wind speed and direction as well as rain sensor, but when I run the program, all of their values are recorded as 0. The only difference is that I'm not posting it to a website, I'm posting the data to my own personal notepad COM4. Temp. humidity and pressure are being recorded just fine though.

**Comment by rpurser47** [comment]
I can only guess based on what you say, but it sounds like the interrupt code isn't running, or that the sensors aren't connected (but I'm assuming you've confirmed that you're seeing the pulses from the sensors, and are sure it's somewhere in the code).  You'll need to give me a lot more detail about your setup before I could guess what's going on.

**Comment by pejandro5** [comment]
Hi Rob,

Many thanks for the reply.  I have a student working on these sensors and I
think he asked for help a little too soon.  We are still mucking around
with the code and the sensors and may have some detailed questions for you
this week.  good to know you are still there and available to help.\

best,

Peter Weiss
Researcher, Environmental Toxicology, UC Santa Cruz

**Comment by rpurser47** [comment]
Switched to email.
